apiVersion: v1
kind: Secret
metadata:
  name: contoso-orders-secrets
  namespace: contoso-orders
type: Opaque
stringData:
  # Filled by pipeline (kubectl create secret ... --dry-run=client | kubectl apply -f -)
  ConnectionStrings__Contoso: ""
  ConnectionStrings__Redis: ""
  AzureServiceBus__ConnectionString: ""
