apiVersion: v1
kind: Service
metadata:
  name: order-accept
  namespace: contoso-orders
spec:
  selector:
    app.kubernetes.io/name: order-accept
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
