apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-notification
  namespace: contoso-orders
  labels:
    app.kubernetes.io/name: order-notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: order-notification
  template:
    metadata:
      labels:
        app.kubernetes.io/name: order-notification
    spec:
      containers:
        - name: order-notification
          image: ${IMAGE_ORDER_NOTIFICATION}
          imagePullPolicy: IfNotPresent
          env:
            - name: DOTNET_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__Redis
              valueFrom:
                secretKeyRef:
                  name: contoso-orders-secrets
                  key: ConnectionStrings__Redis
            - name: AzureServiceBus__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: contoso-orders-secrets
                  key: AzureServiceBus__ConnectionString
            - name: AzureServiceBus__QueueName
              value: "order.processed"
